language: node_js
node_js:
  # https://github.com/nodejs/LTS
  # - "6" # ends April 2019
  - "8" # ends December 2019
  # - "10" # ends April 2021

sudo: false

script:
  - yarn ci
  - if [[ $TRAVIS_BRANCH = "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
      yarn build; yarn global add firebase-tools typescript tslint; firebase deploy --token $FIREBASE_TOKEN --non-interactive;
    fi

after_success:
  - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
      npm run deploy-storybook -- --ci;
    fi
